services:
  client:
    build:
      context: ../apps/client
      target: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  api:
    build:
      context: ../apps/api
      target: production
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      AI_CORE_URL: http://ai-core:8000
    depends_on:
      - ai-core
    restart: unless-stopped

  ai-core:
    build:
      context: ../apps/ai-core
      target: production
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
    restart: unless-stopped
